# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20161010_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='answer',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='result',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='result',
            name='content',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='userscore',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='previous',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.UserScore'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
